<a href="https://colab.research.google.com/github/DominantDuck/pytorch/blob/main/Lesson0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.3.1+cu121


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR[0][2].ndim

1

# Random Tensors

In [ ]:
random_tensor = torch.rand(5,5,5)

random_tensor

tensor([[[0.4781, 0.9266, 0.7459, 0.8970, 0.0323],
         [0.7005, 0.9094, 0.9958, 0.2989, 0.9439],
         [0.8966, 0.8935, 0.2036, 0.5040, 0.7011],
         [0.5911, 0.2857, 0.2295, 0.9128, 0.8403],
         [0.6537, 0.1823, 0.1766, 0.5282, 0.1861]],

        [[0.5822, 0.7157, 0.5983, 0.1980, 0.1429],
         [0.2583, 0.2261, 0.5893, 0.3480, 0.6833],
         [0.3091, 0.9954, 0.4555, 0.4434, 0.8385],
         [0.7131, 0.9646, 0.2751, 0.2684, 0.1617],
         [0.8278, 0.8081, 0.0376, 0.8889, 0.8270]],

        [[0.7366, 0.7174, 0.9754, 0.7327, 0.9431],
         [0.6958, 0.5370, 0.5082, 0.0241, 0.2559],
         [0.6176, 0.5974, 0.9684, 0.7654, 0.4999],
         [0.1921, 0.6653, 0.1758, 0.3218, 0.5694],
         [0.9905, 0.8904, 0.3188, 0.3168, 0.3479]],

        [[0.5448, 0.4183, 0.8511, 0.3826, 0.2442],
         [0.0459, 0.4583, 0.4608, 0.2978, 0.9666],
         [0.6644, 0.9894, 0.9469, 0.3383, 0.2744],
         [0.9682, 0.8171, 0.0793, 0.9915, 0.8029],
         [0.2480, 0.3015,

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224)) #height, with, rgb value
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeros and Ones

In [ ]:
zeros = torch.zeros (size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor.dtype

torch.float32

# Range of Tensors

In [ ]:
torch.arange(start=0,end=1000, step=25)

tensor([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325,
        350, 375, 400, 425, 450, 475, 500, 525, 550, 575, 600, 625, 650, 675,
        700, 725, 750, 775, 800, 825, 850, 875, 900, 925, 950, 975])

In [ ]:
ten_zeroes = torch.zeroes_like

# Tensor Datatypes

In [5]:
test_data = torch.tensor([3.0,6.0,9.0], dtype=None, device=None)

test_data

tensor([3., 6., 9.])

In [6]:
updated_test_data = test_data.type(torch.float16)
updated_test_data

tensor([3., 6., 9.], dtype=torch.float16)

# Get info from tensors

1. Datatype - `tensor.dtype`
2. shape - `tensor.shape`
3. device - `tensor.device`

In [26]:
test_tensor = torch.rand(3,4)
test_tensor

tensor([[0.8041, 0.5726, 0.1328, 0.2593],
        [0.5420, 0.8000, 0.4580, 0.7413],
        [0.6703, 0.6025, 0.8730, 0.1768]])

In [12]:
print(test_tensor)
print(test_tensor.dtype)
print(test_tensor.shape)
print(test_tensor.device)

tensor([[0.9112, 0.0684, 0.6088, 0.1115],
        [0.0214, 0.3849, 0.1358, 0.8353],
        [0.1052, 0.1473, 0.9910, 0.5714]])
torch.float32
torch.Size([3, 4])
cpu


In [28]:
test_tensor = test_tensor.type(torch.float16)
print(test_tensor)
print(test_tensor.dtype)

tensor([[0.8042, 0.5728, 0.1328, 0.2593],
        [0.5420, 0.7998, 0.4580, 0.7412],
        [0.6704, 0.6025, 0.8730, 0.1769]], dtype=torch.float16)
torch.float16


#Manipulating Tensors

Tensor operations include: add, subtract, multiplication, division, and matrix multiplication

In [30]:
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [32]:
#Element wise mutiplication
tensor * tensor

tensor([1, 4, 9])

In [35]:
#Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [36]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.33 ms, sys: 0 ns, total: 1.33 ms
Wall time: 1.23 ms


tensor(14)

Matrix Multiplication rules
1. Inner dimensions must match
2. The resulting matrix has the shape of the **outer dimensions**


In [39]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Fixing tensor shape issues

In [42]:
tensor_B = tensor_B.T

In [43]:
torch.mm(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])